In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
df = pd.read_csv("Global_Landslide_Catalog_Export.csv")
print(df.shape)
print(df.head())

(11033, 31)
   source_name                                        source_link  event_id  \
0          AGU  https://blogs.agu.org/landslideblog/2008/10/14...       684   
1    Oregonian  http://www.oregonlive.com/news/index.ssf/2009/...       956   
2     CBS News  https://www.cbsnews.com/news/dozens-missing-af...       973   
3      Reuters  https://in.reuters.com/article/idINIndia-41450...      1067   
4  The Freeman  http://www.philstar.com/cebu-news/621414/lands...      2603   

               event_date  event_time  \
0  08/01/2008 12:00:00 AM         NaN   
1  01/02/2009 02:00:00 AM         NaN   
2  01/19/2007 12:00:00 AM         NaN   
3  07/31/2009 12:00:00 AM         NaN   
4  10/16/2010 12:00:00 PM         NaN   

                                         event_title  \
0      Sigou Village, Loufan County, Shanxi Province   
1                                Lake Oswego, Oregon   
2  San Ramon district, 195 miles northeast of the...   
3                                   Dailek

In [3]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11033 entries, 0 to 11032
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   source_name                11033 non-null  object 
 1   source_link                10187 non-null  object 
 2   event_id                   11033 non-null  int64  
 3   event_date                 11033 non-null  object 
 4   event_time                 0 non-null      float64
 5   event_title                11033 non-null  object 
 6   event_description          10171 non-null  object 
 7   location_description       10931 non-null  object 
 8   location_accuracy          11031 non-null  object 
 9   landslide_category         11032 non-null  object 
 10  landslide_trigger          11010 non-null  object 
 11  landslide_size             11024 non-null  object 
 12  landslide_setting          10964 non-null  object 
 13  fatality_count             9648 non-null   flo

In [4]:
df = df.fillna(df.median(numeric_only=True))


for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [5]:
le = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

In [6]:
X = df.drop("landslide_category", axis=1)   
y = df["landslide_category"]    

In [7]:
X = X.fillna(0)   
y = y.fillna(y.mode()[0])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

c:\Users\aalia\lenv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [10]:
y_pred = model.predict(X_test)

In [11]:
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.6792025373810603

Confusion Matrix:
 [[   0    0    0    0   48    0    0    0    0    0    0    0]
 [   0    0    0    0   40    0    0    0    0    0    0    0]
 [   0    0    0    0    1    0    0    0    0    0    0    0]
 [   0    0    0    0    2    0    0    0    0    0    0    0]
 [   0    0    0    0 1498    4    0    0    0    0    0    0]
 [   0    0    0    0  437    0    0    0    2    0    0    0]
 [   0    0    0    0   16    0    0    0    0    0    0    0]
 [   0    0    0    0   10    0    0    0    0    0    0    0]
 [   0    0    0    0  135    0    0    0    1    0    0    0]
 [   0    0    0    0    3    0    0    0    0    0    0    0]
 [   0    0    0    0    5    0    0    0    0    0    0    0]
 [   0    0    0    0    5    0    0    0    0    0    0    0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        48
           2       0.00      0.00      0.00        40
    

c:\Users\aalia\lenv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aalia\lenv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\aalia\lenv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [12]:
import joblib
joblib.dump(model, "landslide_model.pkl")

['landslide_model.pkl']